import type { Metadata } from "next";         //metadata 데이터를 위한 데이터
import { Inter } from "next/font/google";
import "./globals.css";
import './style/App.css';
import './style/util.css';
import './style/main.css';

const inter = Inter({ subsets: ["latin"] });  //폰트

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

